const COMMON = {
  selectValueContainer: '[data-testid="nui-select-value-container"]',
};

export const CREATE_FORM_SELECTORS = {
  addFormButton: "add-form-button",
  publishButton: "publish-button",
  addFormElementButton: "add-element-button",
  menuButton: "neeto-molecules-menu-button",
  formDeleteButton: "form-delete-button",
  alertCheckboxButton: "delete-archive-alert-archive-checkbox",
  alertDeleteButton: "delete-archive-alert-delete-button",
  addOptionButton: "add-option-link",
  elementsContainer: "elements-container",
  randomizeSwitchLabel: "randomize-switch-label",
  hideSwitchLabel: "hide-question-toggle-label",
  nuiSwitchLabel: "nui-switch",
  singleChoiceQuestionAddButton: "add-single-choice-element",
  multipleChoiceQuestionAddButton: "add-multiple-choice-element",
  randomizedErrorWarning: "randomized-warning-error-text",
  hiddenErrorWarning: "hide-question-error-text",
  saveChangesButton: "save-changes-button",
  emailDetailsDropdown: "email-more-dropdown",
  deleteEmailButton: "delete-element-button",
  addEmailButton: "add-email-element",
  loadingSpinner: '[data-testid="neeto-ui-spinner"]',
  formGroupQuestion: "form-group-question",
  optionInput: "option-input",
  deleteOptionButton: "delete-option-button",
  emailPreviewGroup: "email-preview-group",
  fieldCodeTextField: "field-code-text-field",
  contextTextField: "content-text-field",
  matrixRowContainer: "matrix-row-container",
  matrixColContainer: "matrix-column-container",
  addMatrixElement: "add-matrix-element",
  addOpinionScaleElement: "add-opinion-scale-element",
  addStarRatingElement: "add-star-rating-element",
};

export const CREATE_FORM_SUBMISSIONS_SELECTORS = {
  submissionTab: "submissions-tab",
};

export const CREATE_FORM_ANALYTICS_SELECTORS = {
  analyticsTab: "analytics-tab",
  insightCount: "insights-count",
  visitMetric: "visits-metric",
  startsMetric: "starts-metric",
  submissionsMetric: "submissions-metric",
  completionRateMetric: "completion-rate-metric",
};

export const CREATE_FORM_SETTINGS_SELECTORS = {
  settingsTab: "settings-tab",
  accessControlCard: "access-control-settings-link",
  accessControlPasswordField: "access-control-password-protected-radio-input",
  securePasswordInput: "password-input-field",
  securePasswordError: "password-input-error",
  noTrackItemCheck: "no-track-radio-item",
  cookieTrackItemCheck: "cookie-track-radio-item",
  uniqueSubmissionCard: "unique-submission-settings-link",
  conditionalLogicCard: "conditional-logic-settings-link",
  addNewCondition: "no-data-primary-button",
  selectValueContainerField: `${COMMON.selectValueContainer}[name="field"]`,
  typeAQuestionSelectValue: "type-a-question-select-option",
  selectValueContainerVerb: `${COMMON.selectValueContainer}[name="verb"]`,
  isEqualToOption: "is-equal-to-select-option",
  selectValueContainerValue: `${COMMON.selectValueContainer}[name="value"]`,
  optionOne: "option-1-select-option",
  selectValueContainerActionType: `${COMMON.selectValueContainer}[name="actionType"]`,
  showAction: "show-select-option",
  selectValueContainerFields: `${COMMON.selectValueContainer}[name="fields"]`,
  emailOption: "email-select-option",
  conditionalLogicDropdown: "conditional-logic-dropdown",
  conditionalLogicDisableButton: "conditions-Disable-button",
};
