export const FORM_SELECTORS = {
    formGroupQuestion: 'form-group-question',
    fullNameGroup: 'full-name-group',
    phoneNumberGroup: 'phone-group',
    emailGroup: 'email-group',
    publishPreviewButton: 'publish-preview-button',
    firstNameField: 'first-name-text-field',
    lastNameField: 'last-name-text-field',
    emailField: 'email-text-field',
    submitButton: 'start-or-submit-button',
    phoneNumberField: 'phone-number-input-field',
    phoneNumberPrefix: 'phone-number-prefix',
    selectCSS: '.neeto-form-react-select__indicator',
    countryCodeSearchInput: 'country-code-search-input',
}